CREATE TABLE IF NOT EXISTS WORK_ROLE(
    role_id IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(50) NOT NULL,
    salary DOUBLE NOT NULL,
    creation_date DATE NOT NULL
)